apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventorymc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventorymc
  template:
    metadata:
      labels:
        app: inventorymc
    spec:
      containers:
      - name: inventorymc
        image: oumaimahamrouni/inventory
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: inventorys
spec:	
  selector:
    app: inventorymc
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080

