apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: oumaimahamrouni/product
        ports:
        - containerPort: 8080
        env:
        - name: SPRING.DATA.MONGODB.URI
          value: mongodb://mongos:27017/product-service
        - name:  eureka.client.serviceurl.defaultzone
          value: http://discovery:8761/eureka
  

---
apiVersion: v1
kind: Service
metadata:
  name: products
spec:	
  selector:
    app: products
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080



